name: Deploy to DigitalOcean Droplet
'on':
  push:
    branches:
      - test
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to DigitalOcean Droplet
        uses: appleboy/ssh-action@master
        with:
          host: ${{secrets.TEST_HOST}}
          username: ${{secrets.USERNAME}}
          key: ${{secrets.TEST_KEY}}
          script: |
            cd inventario_api
            git pull origin master
            pm2 restart api
            echo 'Deployment to digital ocean finished'
